/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventure;

import java.io.IOException;

import adventure.days.day_1.DayOneSolution;

public class App {
  

    public static void main(String[] args) throws IOException 
    {
        System.out.println(DayOneSolution.SolutionPartTwo());
    }
}
